### ISSUE TITLE
NoSuchMethodError Exception 0.1.5

### ISSUE THREAD

**Issue by vladislav-kiva** [opentracing-contrib/java-rabbitmq-client#14]
after updating version from 0.1.4 to 0.1.5 we staring to receive exceptions:

> [ERROR][][reactor-http-nio-3]r.n.h.s.HttpServer                       : [id: 0x2851fafe, L:/172.177.0.3:8888 - R:/10.1.1.30:54308]  java.lang.NoSuchMethodError: io.opentracing.ScopeManager.activate(Lio/opentracing/Span;Z)Lio/opentracing/Scope;
> at io.opentracing.contrib.spring.web.webfilter.TracingOperator.subscribe(TracingOperator.java:73)
> at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
> at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:61)
>

**Comment by malafeev** [comment]
@vladislav-kiva you need to upgrade your tracer to version which is based on OpenTracing API 0.33.0
